export const theme = {
  container: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    backgroundColor: '#121214',
    color: '#e1e1e6',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 24px',
    backgroundColor: '#1a1a1e',
    borderBottom: '1px solid #29292e',
  },
  profileSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    backgroundColor: '#121214',
    padding: '8px 16px',
    borderRadius: '8px',
    border: '1px solid #29292e'
  },
  nameInputBar: {
    display: 'flex',
    gap: '12px',
    backgroundColor: '#1a1a1e',
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid #29292e',
    marginBottom: '20px',
    alignItems: 'center'
  },
  card: {
    backgroundColor: '#1a1a1e',
    borderRadius: '12px',
    border: '1px solid #29292e',
    padding: '32px',
    boxShadow: '0 8px 24px rgba(0,0,0,0.2)',
    width: '100%',
    maxWidth: '420px',
    margin: 'auto',
    textAlign: 'center',
  },
  input: {
    width: '100%',
    padding: '12px 16px',
    backgroundColor: '#121214',
    border: '1px solid #29292e',
    borderRadius: '8px',
    color: '#fff',
    fontSize: '14px',
    marginBottom: '16px',
    boxSizing: 'border-box',
    outline: 'none',
  },
  btnPrimary: {
    width: '100%',
    padding: '12px',
    backgroundColor: '#04d361',
    color: '#000',
    border: 'none',
    borderRadius: '8px',
    fontWeight: 'bold',
    fontSize: '15px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  btnSecondary: {
    padding: '8px 16px',
    backgroundColor: '#29292e',
    color: '#e1e1e6',
    border: '1px solid #323238',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '14px',
  },
  videoWrapper: {
    position: 'relative',
    backgroundColor: '#1a1a1e',
    borderRadius: '12px',
    overflow: 'hidden',
    aspectRatio: '16/9',
    border: '1px solid #29292e',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
  },
  badge: {
    position: 'absolute',
    bottom: '12px',
    left: '12px',
    backgroundColor: 'rgba(0,0,0,0.6)',
    color: '#fff',
    padding: '4px 12px',
    borderRadius: '20px',
    fontSize: '12px',
    backdropFilter: 'blur(4px)',
  },
  videoNameBadge: {
    position: 'absolute',
    top: '12px',
    left: '12px',
    backgroundColor: 'rgba(0,0,0,0.6)',
    color: '#fff',
    padding: '4px 12px',
    borderRadius: '4px',
    fontSize: '13px',
    fontWeight: '500',
    backdropFilter: 'blur(4px)',
    border: '1px solid rgba(255,255,255,0.1)'
  },
  controlBar: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '16px',
    padding: '16px',
    backgroundColor: '#1a1a1e',
    borderTop: '1px solid #29292e',
    position: 'fixed',
    bottom: '0',
    left: '0',
    right: '0',
    zIndex: '10',
  },
  controlBtn: (isActive, isDanger) => ({
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    border: 'none',
    backgroundColor: isDanger ? (isActive ? '#ff4d4d' : '#29292e') : (isActive ? '#04d361' : '#29292e'),
    color: isActive && !isDanger ? '#000' : '#fff',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    fontSize: '18px',
    transition: 'all 0.2s ease',
    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
  })
};
